language: php
php:
  - 5.5
  - 5.6
  - '7'
before_script:
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - pecl install -f ssh2-beta < .noninteractive
install: composer install --dev
script: phpunit -c test/phpunit.xml